---
title: "NATSAP- Process Data"
author: "Sean Raleigh"
date: "August 19, 2015"
output: html_document
---

In this document, we clean the data and store it for use in other models.

## Housekeeping

Load necessary libraries and special functions.

```{r, message = FALSE}
library(beepr)
library(dplyr)
library(ggplot2)
library(knitr)
library(readr)
library(tidyr)
```

```{r}
source("stan_utilities.R")
```

## Read and process data

Load data.

```{r}
natsap <- read.csv("./data/AllClients_rev3.csv")
dose <- read.csv("./data/DoseData_08-19-2015.csv")
```

Clean data and write to the `tidydata` folder.

```{r}

## Subset data

natsap_sub <- natsap %>%
    select(sex = gender,
           ID = programId,
           company = company,
           OQ_A = Z1_A0_Self_SCORE,
           OQ_A_int_dis = Z1_A0_Self_SS1,
           OQ_A_som = Z1_A0_Self_SS2,
           OQ_A_int_rel = Z1_A0_Self_SS3,
           OQ_A_soc_prob = Z1_A0_Self_SS4,
           OQ_A_beh_dys = Z1_A0_Self_SS5,
           OQ_A_crit_it = Z1_A0_Self_SS6,
           OQ_D = Z1_D0_Self_SCORE,
           OQ_D_int_dis = Z1_D0_Self_SS1,
           OQ_D_som = Z1_D0_Self_SS2,
           OQ_D_int_rel = Z1_D0_Self_SS3,
           OQ_D_soc_prob = Z1_D0_Self_SS4,
           OQ_D_beh_dys = Z1_D0_Self_SS5,
           OQ_D_crit_it = Z1_D0_Self_SS6,
           diag = SA_A0_Guardian2_Q4)

dose_sub <- dose %>%
    select(company = company,
           coed = student_sex,
           ID = natsap_id,
           RTCWT = rtc_wt,
           IT = mode_it_mins_week,
           IT_freq = freq_it_week,
           GT = mode_gt_mins_week,
           GT_freq = freq_gt_week,
           RFT = mode_rft_mins_week,
           RFT_freq = freq_rft_week,
           IPFT = mode_ipft_mins_month,
           IPFT_freq = freq_ipft_month,
           PA = mode_pa_mins_week,
           school = mode_school_mins_week)


## Check to make sure program IDs are coded correctly.
## (Visually inspect output to see that the programs match up.)

ID_check_natsap <- natsap_sub %>%
    distinct(ID) %>%
    select(company, ID)
ID_check_dose <- dose_sub %>%
    distinct(ID) %>%
    select(company, ID)

ID_check <- inner_join(ID_check_dose, ID_check_natsap, by = "ID")
as.data.frame(ID_check)


## Get complete cases

natsap_sub <- natsap_sub %>%
    na.omit() %>%
    filter(sex != "")
dose_sub <- dose_sub %>%
    na.omit()


## Validity check:
## OQ total scores have to be between -16 and 240.
## Subscales:
##  -4 <= int_dis <= 68
##  0 <= som <- 32
##  -6 <= int_rel <= 34
##  -2 <= soc_prob <= 30
##  -4 <= beh_dys <= 40
##  0 <= crit_it <= 36
## Programs must be either RTC or WT
## (For example, exclude IOP and TBS.)

natsap_sub <- natsap_sub %>%
    filter(OQ_A >= -16 & OQ_A <= 240) %>%
    filter(OQ_A_int_dis >= -4 & OQ_A_int_dis <= 68) %>%
    filter(OQ_A_som >= 0 & OQ_A_som <= 32) %>%
    filter(OQ_A_int_rel >= -6 & OQ_A_int_rel <= 34) %>%
    filter(OQ_A_soc_prob >= -2 & OQ_A_soc_prob <= 30) %>%
    filter(OQ_A_beh_dys >= -4 & OQ_A_beh_dys <= 40) %>%
    filter(OQ_A_crit_it >= 0 & OQ_A_crit_it <= 36) %>%
    filter(OQ_D >= -16 & OQ_D <= 240) %>%
    filter(OQ_D_int_dis >= -4 & OQ_D_int_dis <= 68) %>%
    filter(OQ_D_som >= 0 & OQ_D_som <= 32) %>%
    filter(OQ_D_int_rel >= -6 & OQ_D_int_rel <= 34) %>%
    filter(OQ_D_soc_prob >= -2 & OQ_D_soc_prob <= 30) %>%
    filter(OQ_D_beh_dys >= -4 & OQ_D_beh_dys <= 40) %>%
    filter(OQ_D_crit_it >= 0 & OQ_D_crit_it <= 36)
    
dose_sub <- dose_sub %>%
    filter(RTCWT != "RTC" | RTCWT != "WT")
    

## Join IDs so our tidy data sets will contain only
## programs for which we have dose data and matched pairs.

natsap_tidy <- semi_join(natsap_sub, dose_sub, by = "ID")
dose_tidy <- semi_join(dose_sub, natsap_sub, by = "ID")


## Get sample sizes for each program (for each sex) and keep only programs with
## more than two matched pairs.

sample_size <- natsap_tidy %>%
    group_by(ID, sex) %>%
    summarize(n = n()) %>%
    spread(sex, n) %>%
    rename(n_female = FEMALE, n_male = MALE) %>%
    replace(is.na(.), 0) %>%
    mutate(n = n_female + n_male)
           
dose_tidy <- dose_tidy %>%
    inner_join(sample_size, by = "ID") %>%
    filter(n > 2)

natsap_tidy <- natsap_tidy %>%
    semi_join(dose_tidy, by = "ID")

## Check that sex is coded correctly for individuals in "male only" and "female only" programs.

check_sex <- dose_tidy %>%
    select(ID, coed, n_female, n_male) %>%
    mutate(check = ifelse((coed == "male only" & n_female > 0) |
                         (coed == "female only" & n_male > 0),
                         FALSE, TRUE),
           correct_sex = ifelse((coed == "male only" & n_female > 0), "MALE", "FEMALE")) %>%
    filter(check == FALSE)

for (i in check_sex$ID) {  # Rewrite sex for data-entry errors.
    correct_sex <- check_sex$correct_sex[check_sex$ID == i]
    natsap_tidy[natsap_tidy$ID == i & natsap_tidy$sex != correct_sex, "sex"] <- correct_sex
}

## Redo the sample size calculations and the joins so that the sample sizes by
## sex are correct again.
## (MAYBE THERE'S A BETTER WAY TO DO THIS!)

sample_size <- natsap_tidy %>%
    group_by(ID, sex) %>%
    summarize(n = n()) %>%
    spread(sex, n) %>%
    rename(n_female = FEMALE, n_male = MALE) %>%
    replace(is.na(.), 0) %>%
    mutate(n = n_female + n_male)
           
dose_tidy <- dose_tidy %>%
    select(-n, -n_female, -n_male) %>%
    inner_join(sample_size, by = "ID")

natsap_tidy <- natsap_tidy %>%
    semi_join(dose_tidy, by = "ID")

## Make OQdiff variable

natsap_tidy <- natsap_tidy %>%
    mutate(OQdiff = OQ_A - OQ_D,   # Positive scores represent improvement
           OQdiff_int_dis = OQ_A_int_dis - OQ_D_int_dis,
           OQdiff_som = OQ_A_som - OQ_D_som,
           OQdiff_int_rel = OQ_A_int_rel - OQ_D_int_rel,
           OQdiff_soc_prob = OQ_A_soc_prob - OQ_D_soc_prob,
           OQdiff_beh_dys = OQ_A_beh_dys - OQ_D_beh_dys,
           OQdiff_crit_it = OQ_A_crit_it - OQ_D_crit_it)
    

## Give programs new random ID, consecutively numbered

J <- NROW(dose_tidy)
set.seed(1234)
new_ID <- sample(1:J, J)

dose_tidy <- dose_tidy %>%
    cbind(new_ID) %>%
    arrange(new_ID)

lookup <- dose_tidy %>%
    select(ID, new_ID)

natsap_tidy <- natsap_tidy %>%
    inner_join(lookup, by = "ID") %>%
    arrange(new_ID)


## Write tidy data sets to csv for convenience

write_csv(dose_tidy, path = "./tidydata/dose_tidy.csv")
write_csv(natsap_tidy, path = "./tidydata/natsap_tidy.csv")
```

Clean up workspace:

```{r}
rm(natsap, dose, natsap_sub, dose_sub, ID_check, ID_check_dose, ID_check_natsap, J, new_ID, lookup, sample_size, check_sex, correct_sex, i)
```

```{r}
beep()
```
